name: build

on:
  - push

jobs:
  site:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: site
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - uses: JamesIves/github-pages-deploy-action@4.0.0
        if: github.ref == 'refs/heads/main'
        with:
          branch: gh-pages
          folder: ./dist
          single-commit: true
          silent: false

  server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '15'
      - run: gradle assemble
      - run: gradle check
